### ISSUE TITLE
Chapter 3: catch2 file not found

### ISSUE THREAD

**Issue by OstrichMan42** [cjdb/cjdb.github.io#12]
In chapter 3 there is an error when using Compiler Explorer;
fatal error: 'catch2/catch_test_macros.hpp' file not found
`#include <catch2/catch_test_macros.hpp>`

It appears that catch2 is not found by Compiler Explorer.

**Comment by cjdb** [comment]
Thanks for the report! I can't reproduce this: did you navigate to Compiler Explorer via the provided link, or by other means?

**Comment by OstrichMan42** [comment]
I used the link given in chapter 2, https://godbolt.org/z/b19Y9Mb5P.
I just noticed there is a new link for chapter three, https://godbolt.org/z/Kdc8aoocj, it works with that one, I don't know why.

**Comment by OstrichMan42** [comment]
Learning has occurred! The green book button lets you choose libraries to include!
The links at the start of each chapter have the necessary libraries included already, how convenient.

**Comment by cjdb** [comment]
Oh, you figured it out, neat :)

There's a disclaimer in Chapter 1 about, but perhaps the first few chapters should stress that you need to open a new session per chapter a little more. WDYT?

**Comment by OstrichMan42** [comment]
I had picked up where I left off from a few weeks ago so I totally forgot about the disclaimer. I think adding the disclaimer to chapters 2 and 3 should solve it for forgetful folks like me.
It might also help to explain why you need a different link each time, maybe in chapter 3, since if the reader is just following the tutorial they won't see the difference. Chapter 3 is also the second time that a library is included so showing where they are coming from, and that they are coming from somewhere, is good knowledge even if it won't be used in the module.

**Comment by cjdb** [comment]
@OstrichMan42 I've been thinking about this again recently (I applied the changes locally when we last spoke but haven't pushed them yet due to changes I've been making), and am wondering if it would be a good idea to have something like this in the first chapter:

> We will be using Compiler Explorer with two different configurations based on the each chapter's needs. You do not need to worry about how to configure it: that's already been taken care of for you. Each chapter will clearly state which preloaded configuration you need, and link to it. However, you may like to bookmark these configurations now:
>
> * [Compiler Explorer (printing)](https://godbolt.org/z/xToMqrGhP)
> * [Compiler Explorer (testing)](https://godbolt.org/z/KoK7jv189)

Finally, each chapter would have one of these two notes, based on the chapter in question's needs:

![A note that reads "This chapter uses "Compiler Explorer (printing)"](https://github.com/cjdb/cjdb.github.io/assets/8622748/543d7a50-e3ca-450e-8597-c084e1bb777e)

![A note that reads "This chapter uses "Compiler Explorer (testing)"](https://github.com/cjdb/cjdb.github.io/assets/8622748/167ad131-c227-4657-9251-fc36df1bf8fa)

**Comment by OstrichMan42** [comment]
The added paragraph of explanation covers my confusion on the why, and the notes cover the how.
The notes aren't invasive so I think they're a good addition.
